<?php

namespace Gestion\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesRepository extends EntityRepository
{
}
