<?php

namespace Gestion\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesRepository extends EntityRepository
{
}
