<?php

namespace Gestion\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionsRepository extends EntityRepository
{
}
