accueil_homepage:
    path:     /
    defaults: { _controller: AccueilBundle:Default:Accueil }
aimer:
    path:     /accueil/aimer/{id}
    defaults: { _controller: AccueilBundle:Default:aimer }
ne_pas_aimer:
    path:     /accueil/nepasaimer/{id}
    defaults: { _controller: AccueilBundle:Default:nepasaimer }