accueil_homepageNO:
    path:     /
    defaults: { _controller: AccueilBundle:Default:Accueil }
aimerNO:
    path:     /accueil/aimer/{id}
    defaults: { _controller: AccueilBundle:Default:aimer }
    options:
        expose: true

ne_pas_aimerNO:
    path:     /accueil/nepasaimer/{id}
    defaults: { _controller: AccueilBundle:Default:nepasaimer }
    options:
        expose: true
