admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

accueil:
    resource: "@AccueilBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin