gestion_missions:
    resource: "@GestionBundle/Resources/config/routing/missions.yml"
    prefix:   /missions

gestion_sites:
    resource: "@GestionBundle/Resources/config/routing/sites.yml"
    prefix:   /sites

gestion_clients:
    resource: "@GestionBundle/Resources/config/routing/clients.yml"
    prefix:   /clients

gestion_demandes:
    resource: "@GestionBundle/Resources/config/routing/demandes.yml"
    prefix:   /demandes

gestion_homepage:
    path:     /hello/{name}
    defaults: { _controller: GestionBundle:Default:index }
        
fichier_ajout:
    path:     /fichier
    defaults: { _controller: GestionBundle:Default:fichier }

demande_ajout:
    path:     /demande
    defaults: { _controller: GestionBundle:Default:demande }
    
notifications:
    path :    /notifier
    defaults: { _controller: GestionBundle:Default:notifier }
    
modifetat:
    path :    accueil/modifetat/{id}/{etat}
    defaults: { _controller: GestionBundle:Default:modifetat }
    options:
        expose: true

commentersansfichier:
    path :    accueil/commenter/{id}/{contenu}
    defaults: { _controller: GestionBundle:Default:commentersansfichier }
    options:
        expose: true

demandes_reporting:
    path :    accueil/chiffres
    defaults: { _controller: GestionBundle:Default:demandeschiffres }
demandes_effacer_accueil:
    path :    accueil/effacerdemande/{id}
    defaults: { _controller: GestionBundle:Default:effacerdemandeaccueil }
    options:
        expose: true

accueil_homepage:
    path:     /
    defaults: { _controller: GestionBundle:Default:Accueil }
aimer:
    path:     /accueil/aimer/{id}
    defaults: { _controller: GestionBundle:Default:aimer }
    options:
        expose: true

ne_pas_aimer:
    path:     /accueil/nepasaimer/{id}
    defaults: { _controller: GestionBundle:Default:nepasaimer }
    options:
        expose: true

exporterDemande:
    path:     /export/{id}
    defaults: { _controller: GestionBundle:Default:exporterdemande }
    options:
        expose: true
        
exporterTousDemande:
    path:     /exporter/all
    defaults: { _controller: GestionBundle:Default:exporterTousDemandes }
    options:
        expose: true
    

        
        
        
        
        